### PR TITLE
Minor dependency updates, enhancement additions and bug fixes

### LINKED ISSUE #24: Emit event on outgoing command

### LINKED ISSUE #31: Allow sending messages with preceding "#" in channel name
### Feature request

Invocation of the `<ChatClient>.say()` method when "#" is included at the beginning of the channel name currently results in a `ValidationError: Channel name "#channel" is invalid/malformed` error.

<hr>

As someone porting over from another IRC library which allows such behavior, my code is written in such a way so that messages must be able to send with the preceding "#" before the channel name. Perhaps it would be worthwhile to implement such functionality as well?

### LINKED ISSUE #91: Promise rejections mixin not updated for newly added methods
https://github.com/robotty/dank-twitch-irc/blob/master/lib/mixins/ignore-promise-rejections.ts

setColor should probably be there.

### LINKED ISSUE #108: Have client.connect return a promise to be resolved once client is ready

### PR DESCRIPTION
**Pull request by TroyDota**
Fixes #108 
Fixes #31 
Fixes #91 
Fixes #24

Minor dependency updates, enhancement additions and bug fixes.

### CODE REVIEW

**Comment by TroyDota** [comment]
Ill fix the formatting if the code is correct. I don't want to apply a commit and fix formatting which might cause a messy pr. I should have fixed formatting on each commit which is my bad.

**Review by RAnders00 — APPROVED** [review]
Thanks a lot! ❤️

**Comment by RAnders00** [comment]
Looks like you‘ll have to run prettier, then we can merge this.

**Comment by TroyDota** [comment]
Sure 👍 
seems good now

**Pull request merged**
